### ISSUE TITLE
I can't see anything in hololens2

### ISSUE THREAD

**Issue by qfy123** [microsoft/mixed-reality-robot-interaction-demo#16]
hello,I'm following the youtube guide,but I can't see anything in my hololens2 except this
![image](https://user-images.githubusercontent.com/84958161/155946362-2dc8043d-5250-4763-b6e4-00cc924245d4.png)
I don't why,I uploaded the asa config file but it's still like this

**Comment by EricVoll** [comment]
Hi @qfy123

Interesting...
When building the app, did you select the ManagerScene, ConfigScene and the Demo2Scene (as it can be seen [here](https://youtu.be/4G3wjPIs4Fc?t=670))? It's also important that the ManagerScene is the first one in the list, because that's the scene the app loads by default. It looks like its failing to load the ConfigScene.

Maybe in the ManagerScene check the "Loader" GameObject, which is responsible of loading the scenes. There is a flag there to not load anything - maybe that is set for some reason?

In the Unity editor when pressing play, while only the manager scene is loaded, can you see the Config UI?

**Comment by EricVoll** [comment]
This might be a networking or maybe authentication issue - yes.
Please validate that your asa config file has the correct information (including the asa region) and make sure that you have public internet access. Usually you don't have to open any specific networking ports or so. 
Did you build the app from Unity yourself, or did you download and deploy the released version from github?

**Comment by qfy123** [comment]
the logs
`Attempting to create anchor `
`CloudManager_Error Server Error:Service unavailable or unspecified error found`
`Error While Creating The Anchor:Exiting` 
`Warn:Max Proximity Light Count (2) Exceeded `

I built it from Unity myself,and I have tried two asa regions, eastus and southeast Asia. Maybe I should change the network environment.

**Comment by SatishBoddu-MSFT** [comment]
**Related Q&A Thread:** https://docs.microsoft.com/en-us/answers/questions/753539/index.html

**Comment by EricVoll** [comment]
So from your screenshots it looks like the Unity project is broken ("Script cannot be loaded"), which is weird because if I clone this project freshly, its working just fine.
If a Unity project is opened in a Unity Version different than the one used to create the project, Unity will try to convert the project. In my experience that process breaks very often. This project was last edited with version 20129.4.10f1. Could you try to re-clone the project from GitHub into an empty directory, and open it using this exact Unity Version?

**Comment by EricVoll** [comment]
I just verified that this is the case for me (re-cloning and opening the project). In my case the MRTK Toolkit is loaded properly and ASA seems to work.

**Comment by qfy123** [comment]
The Unity version in the screenshot is 2020.3LTS. As you said, I use the 2019.4.10f1 version, everything is normal, the project can be loaded and the app can be built normally. On hololens2, the orange cube was initially in front of the robot, and the next instant it moved under the robot's chassis, and I had to crouch down to grab it. I've tried ASA domains in three different regions:eastus, southeast Asia, and central korea, and none can create anchors. The log output is still `CloudManager_ErrorServerError: Service unavailable or unspecified error found`. I don't think it should be a problem with ASAconfig.
Also, I found that in the YouTube tutorial of this demo, the part about docker, my docker terminal is missing the following part
![image](https://user-images.githubusercontent.com/84958161/156206672-8ceeeea5-9870-489d-a34a-c87038fa57ec.png)

**Comment by EricVoll** [comment]
You do not have to guess your domain. You can find it under portal.azure.com in your Azure Spatial Anchors resource, in the overview tab under "Account Domain": ...
![image](https://user-images.githubusercontent.com/28082576/156212042-21e45045-8a71-466c-8d45-30a526b61e52.png)

**Comment by EricVoll** [comment]
I'm currenlty not sure if the missing ROS Logs cause any problems or if its maybe just a verbosity level issue. In any case, it doesn't influence ASA.

**Comment by qfy123** [comment]
OK, now I can create anchors after referring to this [document.](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-ios?tabs=azure-portal#configure-account-identifier-and-key) But new problems arose. When I set the point, the robot shows the path, but it doesn't move to the point

**Comment by EricVoll** [comment]
May I ask what the problems were?
Are you building on macOS for iOS? We never had the chance to test this demo with iOS, although it should work out of the box as well. In another comment you mentioned you are building for HL2 - I didn't know that it is possible to deploy HL2 apps without Visual Studio...

Tha other problem seems to be a ROS problem with the docker container. We noticed that (mostly due to gazebo) the container sometimes fails to load. If I guess correctly, your container never prints "First Odom received", right?

**Comment by qfy123** [comment]
Oh sorry, I don't use iOS, I just refer to this [part](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-ios?tabs=azure-portal#configure-the-account-information) of the documentation, it's the same as the Hololens [documentation.](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-hololens?tabs=azure-portal#configure-the-account-information)
When I connect to the docker host, the terminal output is as follows:
```
2022-03-02 09:28:22+0000 [-] [INFO] [1646213302.138555, 101.348000]: Client connected.  1 clients total.
2022-03-02 09:28:22+0000 [-] [INFO] [1646213302.144723, 101.354000]: Client connected.  2 clients total.
2022-03-02 09:28:22+0000 [-] [INFO] [1646213302.415841, 101.625000]: [Client 1] Subscribed to /clock
2022-03-02 09:28:22+0000 [-] [INFO] [1646213302.418740, 101.628000]: [Client 1] Subscribed to /clock
2022-03-02 09:28:22+0000 [-] [INFO] [1646213302.430900, 101.640000]: [Client 1] Subscribed to /joint_states
2022-03-02 09:28:22+0000 [-] [INFO] [1646213302.454194, 101.663000]: [Client 1] Subscribed to /odometry/filtered
2022-03-02 09:28:22+0000 [-] [INFO] [1646213302.455690, 101.665000]: [Client 1] Subscribed to /joint_states
2022-03-02 09:28:22+0000 [-] [INFO] [1646213302.456832, 101.666000]: [Client 1] Subscribed to /odometry/filtered
2022-03-02 09:28:22+0000 [-] [INFO] [1646213302.462788, 101.672000]: [Client 1] Subscribed to /move_base/TrajectoryPlannerROS/local_plan
2022-03-02 09:28:22+0000 [-] [INFO] [1646213302.464334, 101.673000]: [Client 1] Subscribed to /move_base/TrajectoryPlannerROS/local_plan
2022-03-02 09:28:22+0000 [-] [INFO] [1646213302.470997, 101.680000]: [Client 1] Subscribed to /transform_output
2022-03-02 09:28:22+0000 [-] [INFO] [1646213302.471964, 101.681000]: [Client 1] Subscribed to /transform_output


```
Then I click Set Position, the output of the terminal does not change, the log output in HL2 is `Published move_base_goal_point`.And the wheels are not moving

**Comment by qfy123** [comment]
Hello, now I finally solved all the problems, it seems to be the problem of the docker container. After I switched to ubuntu, I ran docker again, and the console output was the same as in the video. The missing part was there. Jackal can move, everything is normal. Thank you for your help these days!

**Comment by EricVoll** [comment]
Hey @qfy123 great to hear! Thanks for commenting that everything seems to work now. I'd still love to know what the issue was - but I guess we won't find out this time :) 
I wish you all the best of luck with your dev efforts in MR and feel free to reach out if you have questions about the demo.
