### ISSUE TITLE
Replacing the robot with Import URDF 

### ISSUE THREAD

**Issue by saratrajput** [microsoft/mixed-reality-robot-interaction-demo#17]
Hello. Thank you for your work.

I wanted to replace the robot in this package with another and tried to follow the tutorial in the Wiki. But I wasn't able to do so with the method described there. Instead, I imported the robot using the URDF Importer package from Unity. I'm wondering if there is any difference between the two methods and if we lose any functionality if we don't use the method described in the Wiki.

**Comment by EricVoll** [comment]
Hi @saratrajput 
In principle, the URDF Importer from Unity is based on the URDF Importer from the ROS# package, so generally, they should behave the same. 
But the URDF Importer does attach a few Behavior Scripts for Joints etc., which are used in the [Joint State Subscriber Script](https://github.com/microsoft/mixed-reality-robot-interaction-demo/blob/main/MS_MR_Demo1/Assets/RosSharp/Scripts/RosBridgeClient/RosCommuncation/JointStateSubscriber.cs). Since the Unity importer (if at all - I'm not sure since I haven't used the Unity importer so far) attatches any scripts to the joints, then they will be different scripts, and therefore unusable by the JointStateSubscriber.

Depending on the robot you have, this might be a problem or not (e.g. not moving wheels for example is probably ok, but not-moving legs for a legged robot is probably unacceptable...). But after the import you could manually fix the situation by attaching the right scripts to the joints and setting the references.

**Comment by saratrajput** [comment]
Thank you @EricVoll for the detailed response.

**Comment by EricVoll** [comment]
Welcome, hopefully, it helps to solve your problem.
