### ISSUE TITLE
iOS Unity Packages(json file) required quite some reword

### ISSUE THREAD

**Issue by mitsiu** [microsoft/mixed-reality-robot-interaction-demo#19]
As a curiosity, did you ever think of update testing with the Spot instead of Jackal only?

**Comment by mitsiu** [comment]
Json file update sorted for iOS build and deploy

**Comment by EricVoll** [comment]
Hi @mitsiu 
The iOS part of this repository was never really tested, because we didn't have access to a macOS device running XCode to deploy anything. But did you get it running? If yes, feel free to create a PR with your changes, then we can merge it for others to use as well.

As for your question with spot: Yes, we do have an internal app based on this one, where we can send spot around. Unfortunately that app is not open source.
